#!/bin/sh
#
# dhv - file viewer
#
# In my records, I reference files containing evidence (images, etc.) by their basename (i.e. no location).
# The name must be unique in the entire evidence directory. The reason for this is so that I can freely
# reorganise the files without breaking the references.
#
# This script (run in the root of the evidence directory) finds a file and invokes a suitable viewer for it.
#
# Usage: dhv <basename>

base=$(basename "$1")
full=$(find . -name "*${base}*")

if [ "${full}" = "" ] ; then
	echo "dhv: cannot find ${base}"
	exit 1
fi

if [ -d "${full}" ] ; then
	viewer=ls
else
	typ=$(echo "${full}" | sed -e 's/^.*\.\([^\.]*\)$/\1/')

	case "${typ}" in
		"pdf" | "PDF" )
			viewer=xpdf
			;;
		"djvu" | "DJVU" )
			viewer=djview
			;;
		"txt" | "TXT" | "text" )
			viewer=less
			;;
		"odt" | "ods" | "csv" | "CSV" | "docx" | "doc" | "xlsx" | "xls" )
			viewer=libreoffice 
			;; 
		*)
			viewer=nsxiv 
			;; 
	esac
fi

echo "${full}  using ${viewer} viewer"

${viewer} "${full}"
